# https://clementbm.github.io/github%20action/jekyll/link%20checking/2020/05/31/automatically-validate-links-on-jekyll-website.html
name: CheckLinks
on:
  push:
    branches:
      - pages
  pull_request:
    branches:
      - pages

jobs:
  checklinks:
    name: Linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Setup Rubygems, Bundler, jekyll
        run: | 
          sudo apt update
          sudo apt -y install make build-essential ruby ruby-dev
          sudo gem install jekyll bundler
          sudo bundle install
      - name: Build jekyll website with drafts
        run: sudo bundle exec jekyll build --drafts
      - name: Check for broken links
        run: |
          sudo bundle exec htmlproofer --log-level :debug ./_site &> links.log
        continue-on-error: true
      - name: Archive log links
        uses: actions/upload-artifact@v1
        with:
          name: links-check.log
          path: links.log
